---
- hosts: localhost
  tasks:
    - name: Setup Lightsail Instance
      ansible.builtin.include_role:
        name: terraform

- hosts: lightsail
  tasks:
    - name: Refresh inventory to ensure new instaces exist in inventory
      meta: refresh_inventory

    - name: Install Outline Server
      ansible.builtin.include_role:
        name: outline

