---
- name: Init
  ansible.builtin.shell:
    cmd: "terraform init"
    chdir: "{{role_path}}/files/{{directory}}"
  loop:
    - tfstate
    - lightsail
  loop_control:
    loop_var: directory
  changed_when: false

- name: Bootstrap
  community.general.terraform:
    state: present
    project_path: "{{role_path}}/files/tfstate"
    variables:
      region: "{{AWS_REGION}}"
  register: BACKEND

- name: Apply
  community.general.terraform:
    state: present
    project_path: "{{role_path}}/files/lightsail"
    variables:
      region: "{{AWS_REGION}}"
    backend_config:
      region: "{{BACKEND.outputs.region.value}}"
      bucket: "{{BACKEND.outputs.bucket.value}}"
      key: "terraform.tfstate"
      encrypt: true
